import { NextResponse } from "next/server";
import nodemailer from "nodemailer";

export function generateGoogleMeetLink(): string {
  const chars = "abcdefghijklmnopqrstuvwxyz";
  const gen = (len: number) =>
    Array.from({ length: len }, () => chars[Math.floor(Math.random() * chars.length)]).join("");
  return `https://meet.google.com/${gen(3)}-${gen(4)}-${gen(3)}`;
}

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { fullName, schoolName, schoolSize, email, phone, dateTime, message } = body;

    if (!fullName || !schoolName || !email || !phone || !dateTime) {
      return NextResponse.json(
        { success: false, error: "Required fields are missing." },
        { status: 400 }
      );
    }

    if (!/^[a-zA-Z0-9._%+-]+@gmail\.com$/.test(email)) {
      return NextResponse.json(
        { success: false, error: "Only Gmail addresses are accepted." },
        { status: 400 }
      );
    }

    let cleanPhone = phone.replace(/[\s\-\+\(\)]/g, "");
    if (cleanPhone.startsWith("91")) {
      cleanPhone = cleanPhone.slice(2);
    }
    if (!/^\d{10}$/.test(cleanPhone)) {
      return NextResponse.json(
        { success: false, error: "Invalid phone number. Must be a valid 10-digit mobile number." },
        { status: 400 }
      );
    }

    const meetLink = generateGoogleMeetLink();

    const emailContent = `
      <div style="font-family: Arial, sans-serif; color: #1e293b; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e2e8f0; border-radius: 12px;">
        <h2 style="color: #4f46e5; border-bottom: 2px solid #e2e8f0; padding-bottom: 10px; margin-top: 0;">New Demo Request Received</h2>
        <p>A new demo has been scheduled with the following details:</p>
        <table border="0" cellpadding="8" style="width: 100%; border-collapse: collapse; margin-top: 15px;">
          <tr style="background-color: #f8fafc;">
            <td style="padding: 10px; border: 1px solid #e2e8f0; font-weight: bold; width: 35%;">Full Name</td>
            <td style="padding: 10px; border: 1px solid #e2e8f0;">${fullName}</td>
          </tr>
          <tr>
            <td style="padding: 10px; border: 1px solid #e2e8f0; font-weight: bold;">School Name</td>
            <td style="padding: 10px; border: 1px solid #e2e8f0;">${schoolName}</td>
          </tr>
          <tr style="background-color: #f8fafc;">
            <td style="padding: 10px; border: 1px solid #e2e8f0; font-weight: bold;">School Size</td>
            <td style="padding: 10px; border: 1px solid #e2e8f0; text-transform: capitalize;">${schoolSize}</td>
          </tr>
          <tr>
            <td style="padding: 10px; border: 1px solid #e2e8f0; font-weight: bold;">Work Email</td>
            <td style="padding: 10px; border: 1px solid #e2e8f0;"><a href="mailto:${email}">${email}</a></td>
          </tr>
          <tr style="background-color: #f8fafc;">
            <td style="padding: 10px; border: 1px solid #e2e8f0; font-weight: bold;">Phone Number</td>
            <td style="padding: 10px; border: 1px solid #e2e8f0;">${phone}</td>
          </tr>
          <tr>
            <td style="padding: 10px; border: 1px solid #e2e8f0; font-weight: bold;">Preferred Date & Time</td>
            <td style="padding: 10px; border: 1px solid #e2e8f0; font-weight: 500;">
              ${new Date(dateTime).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' })}
            </td>
          </tr>
          <tr style="background-color: #f8fafc;">
            <td style="padding: 10px; border: 1px solid #e2e8f0; font-weight: bold; vertical-align: top;">Additional Details</td>
            <td style="padding: 10px; border: 1px solid #e2e8f0; white-space: pre-wrap;">${message || "None provided"}</td>
          </tr>
          <tr>
            <td style="padding: 10px; border: 1px solid #e2e8f0; font-weight: bold; vertical-align: top;">Google Meet Link</td>
            <td style="padding: 10px; border: 1px solid #e2e8f0;"><a href="${meetLink}" target="_blank" style="color: #4f46e5; font-weight: 500;">${meetLink}</a></td>
          </tr>
        </table>
        <div style="margin-top: 25px; padding-top: 15px; border-top: 1px solid #e2e8f0; font-size: 11px; color: #64748b; text-align: center;">
          This demo request was automatically generated by the EduTrio Platform.
        </div>
      </div>
    `;

    const userEmailContent = `
      <div style="font-family: Arial, sans-serif; color: #1e293b; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e2e8f0; border-radius: 12px;">
        <div style="background: linear-gradient(135deg, #4f46e5 0%, #7c3aed 100%); padding: 30px; border-radius: 12px 12px 0 0; text-align: center; color: white;">
          <h1 style="margin: 0; font-size: 24px; font-weight: 700; letter-spacing: -0.025em;">Demo Confirmed!</h1>
          <p style="margin: 8px 0 0 0; opacity: 0.9; font-size: 15px;">We are excited to connect with you.</p>
        </div>
        <div style="padding: 24px; background-color: #ffffff; border-radius: 0 0 12px 12px;">
          <p style="font-size: 16px; line-height: 1.6; margin-top: 0;">Hello <strong>${fullName}</strong>,</p>
          <p style="font-size: 15px; line-height: 1.6; color: #4b5563;">Thank you for scheduling a personalized demo with EduTrio. We've reserved the time for you and look forward to showing you how we can transform your school's operations.</p>
          
          <div style="background-color: #f8fafc; border: 1px solid #e2e8f0; border-radius: 12px; padding: 20px; margin: 24px 0;">
            <h3 style="margin-top: 0; color: #1e293b; font-size: 16px; border-bottom: 1px solid #e2e8f0; padding-bottom: 8px;">Meeting Details</h3>
            <table style="width: 100%; border-collapse: collapse; font-size: 14px;">
              <tr>
                <td style="padding: 6px 0; color: #64748b; width: 35%;">School Name:</td>
                <td style="padding: 6px 0; font-weight: 600; color: #1e293b;">${schoolName}</td>
              </tr>
              <tr>
                <td style="padding: 6px 0; color: #64748b;">Date & Time:</td>
                <td style="padding: 6px 0; font-weight: 600; color: #1e293b;">
                  ${new Date(dateTime).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' })}
                </td>
              </tr>
            </table>
          </div>

          <div style="text-align: center; margin: 30px 0;">
            <p style="font-size: 14px; color: #64748b; margin-bottom: 12px;">Join the video call at the scheduled time using the link below:</p>
            <a href="${meetLink}" target="_blank" style="display: inline-block; background: linear-gradient(135deg, #4f46e5 0%, #7c3aed 100%); color: white; padding: 12px 30px; font-weight: 600; text-decoration: none; border-radius: 9999px; font-size: 15px;">Join Google Meet</a>
            <p style="font-size: 12px; color: #94a3b8; margin-top: 12px;">Alternative link: <a href="${meetLink}" style="color: #4f46e5; text-decoration: underline;">${meetLink}</a></p>
          </div>

          <hr style="border: 0; border-top: 1px solid #e2e8f0; margin: 24px 0;" />
          
          <p style="font-size: 14px; line-height: 1.5; color: #4b5563; margin-bottom: 0;">
            If you need to reschedule or have any questions before our meeting, please reply directly to this email.
          </p>
        </div>
        <div style="padding: 15px; font-size: 11px; color: #94a3b8; text-align: center;">
          Sent by EduTrio Platform. © ${new Date().getFullYear()} EduTrio. All rights reserved.
        </div>
      </div>
    `;

    // Check if SMTP details are provided.
    const hasSmtpConfig = process.env.SMTP_HOST && process.env.SMTP_USER && process.env.SMTP_PASS;

    if (!hasSmtpConfig) {
      console.warn("=================================================");
      console.warn("WARNING: SMTP credentials not set in environment (.env.local).");
      console.warn("Logged scheduled demo details for tiwarishubham5332@gmail.com:");
      console.log("Full Name: ", fullName);
      console.log("School: ", schoolName);
      console.log("Size: ", schoolSize);
      console.log("Email: ", email);
      console.log("Phone: ", phone);
      console.log("Date/Time: ", dateTime);
      console.log("Message: ", message);
      console.log("Google Meet Link: ", meetLink);
      console.warn("=================================================");

      return NextResponse.json({
        success: true,
        meetLink,
        message: "Demo saved locally. Configure SMTP_HOST, SMTP_USER, SMTP_PASS in .env.local to send real emails."
      });
    }

    const transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST,
      port: parseInt(process.env.SMTP_PORT || "587"),
      secure: process.env.SMTP_SECURE === "true" || process.env.SMTP_PORT === "465",
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS,
      },
    });

    // 1. Send Admin Notification Email
    await transporter.sendMail({
      from: process.env.SMTP_FROM || `"EduTrio Demo Scheduler" <${process.env.SMTP_USER}>`,
      to: "tiwarishubham5332@gmail.com",
      subject: `New Demo Scheduled: ${schoolName} - ${fullName}`,
      html: emailContent,
    });

    // 2. Send User Confirmation Email
    await transporter.sendMail({
      from: process.env.SMTP_FROM || `"EduTrio Demo Scheduler" <${process.env.SMTP_USER}>`,
      to: email,
      subject: `Demo Confirmed: EduTrio Platform - ${schoolName}`,
      html: userEmailContent,
    });

    return NextResponse.json({ success: true, meetLink });
  } catch (error) {
    console.error("Error sending email:", error);
    const errorMessage = error instanceof Error ? error.message : "Failed to send email";
    return NextResponse.json(
      { success: false, error: errorMessage },
      { status: 500 }
    );
  }
}
