import { NextResponse } from "next/server";
import nodemailer from "nodemailer";

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { fullName, schoolName, schoolSize, email, phone, dateTime, message } = body;

    const emailContent = `
      <div style="font-family: Arial, sans-serif; color: #1e293b; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e2e8f0; rounded-corners: 12px;">
        <h2 style="color: #4f46e5; border-bottom: 2px solid #e2e8f0; padding-bottom: 10px; margin-top: 0;">New Demo Request Received</h2>
        <p>A new demo has been scheduled with the following details:</p>
        <table border="0" cellpadding="8" style="width: 100%; border-collapse: collapse; margin-top: 15px;">
          <tr style="background-color: #f8fafc;">
            <td style="padding: 10px; border: 1px solid #e2e8f0; font-weight: bold; width: 35%;">Full Name</td>
            <td style="padding: 10px; border: 1px solid #e2e8f0;">${fullName}</td>
          </tr>
          <tr>
            <td style="padding: 10px; border: 1px solid #e2e8f0; font-weight: bold;">School Name</td>
            <td style="padding: 10px; border: 1px solid #e2e8f0;">${schoolName}</td>
          </tr>
          <tr style="background-color: #f8fafc;">
            <td style="padding: 10px; border: 1px solid #e2e8f0; font-weight: bold;">School Size</td>
            <td style="padding: 10px; border: 1px solid #e2e8f0; text-transform: capitalize;">${schoolSize}</td>
          </tr>
          <tr>
            <td style="padding: 10px; border: 1px solid #e2e8f0; font-weight: bold;">Work Email</td>
            <td style="padding: 10px; border: 1px solid #e2e8f0;"><a href="mailto:${email}">${email}</a></td>
          </tr>
          <tr style="background-color: #f8fafc;">
            <td style="padding: 10px; border: 1px solid #e2e8f0; font-weight: bold;">Phone Number</td>
            <td style="padding: 10px; border: 1px solid #e2e8f0;">${phone}</td>
          </tr>
          <tr>
            <td style="padding: 10px; border: 1px solid #e2e8f0; font-weight: bold;">Preferred Date & Time</td>
            <td style="padding: 10px; border: 1px solid #e2e8f0; font-weight: 500;">
              ${new Date(dateTime).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' })}
            </td>
          </tr>
          <tr style="background-color: #f8fafc;">
            <td style="padding: 10px; border: 1px solid #e2e8f0; font-weight: bold; vertical-align: top;">Additional Details</td>
            <td style="padding: 10px; border: 1px solid #e2e8f0; white-space: pre-wrap;">${message || "None provided"}</td>
          </tr>
        </table>
        <div style="margin-top: 25px; padding-top: 15px; border-top: 1px solid #e2e8f0; font-size: 11px; color: #64748b; text-align: center;">
          This demo request was automatically generated by the EduTrio Platform.
        </div>
      </div>
    `;

    // Check if SMTP details are provided.
    const hasSmtpConfig = process.env.SMTP_HOST && process.env.SMTP_USER && process.env.SMTP_PASS;

    if (!hasSmtpConfig) {
      console.warn("=================================================");
      console.warn("WARNING: SMTP credentials not set in environment (.env.local).");
      console.warn("Logged scheduled demo details for tiwarishubham5332@gmail.com:");
      console.log("Full Name: ", fullName);
      console.log("School: ", schoolName);
      console.log("Size: ", schoolSize);
      console.log("Email: ", email);
      console.log("Phone: ", phone);
      console.log("Date/Time: ", dateTime);
      console.log("Message: ", message);
      console.warn("=================================================");

      return NextResponse.json({
        success: true,
        message: "Demo saved locally. Configure SMTP_HOST, SMTP_USER, SMTP_PASS in .env.local to send real emails."
      });
    }

    const transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST,
      port: parseInt(process.env.SMTP_PORT || "587"),
      secure: process.env.SMTP_SECURE === "true" || process.env.SMTP_PORT === "465",
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS,
      },
    });

    await transporter.sendMail({
      from: process.env.SMTP_FROM || `"EduTrio Demo Scheduler" <${process.env.SMTP_USER}>`,
      to: "tiwarishubham5332@gmail.com",
      subject: `New Demo Scheduled: ${schoolName} - ${fullName}`,
      html: emailContent,
    });

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error("Error sending email:", error);
    const errorMessage = error instanceof Error ? error.message : "Failed to send email";
    return NextResponse.json(
      { success: false, error: errorMessage },
      { status: 500 }
    );
  }
}
